### ISSUE TITLE
init_copy never used

### ISSUE THREAD

**Issue by inspirit** [pmed/fixed_size_function#1]
Hi u seem to mistakenly name init_copy[_] with underscore so it never actually got called:
https://github.com/pmed/fixed_size_function/blob/master/fixed_size_function.hpp#L298

I was wondering what is the purpose in defining MaxSize for function wrapper?

**Comment by pmed** [comment]
Thanks, fixed.

This is a demo project for a class like std::function that avoids dynamic memory allocation. It's based on a topic here: http://rsdn.ru/forum/cpp/5732236 (in Russian).

MaxSize is the maximum size for internal buffer.
